select * from customer limit 20


--Q1. What is the total revenue generated by male vs. female customers?

Select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased, Round(Avg(review_rating::numeric),2) as "Avrage Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,
Round(Avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

Select subscription_status,
COUNT(customer_id) as total_customer,
Round(Avg(purchase_amount),2) as Avg_spend,
Round(Sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

Select item_purchased,
Round(100 * Sum(CASE When discount_applied = 'Yes' Then 1 Else 0 End)/ Count (*),2) as discount_rate
From customer
group by item_purchased
order by discount_rate desc limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
Select customer_id, previous_purchases,
CASE
	When previous_purchases = 1 Then 'New'
	When previous_purchases BETWEEN 2 AND 10 Then 'Returning'
	Else 'Loyal'
	END AS customer_segment
From customer
)

select customer_segment, count (*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
count (customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
Select age_group,
Sum(purchase_amount) as total_revenue
From customer
group by age_group
order by total_revenue desc;